version: '3.9'

services:
  db:
    image: postgres:latest
    container_name: devopsfinal
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    networks:
      - vote-api-network

  vote-api:
    build:
      context: vote-api
    ports:
      - "8080:8080"
    environment:
      PG_URL: "postgres://user:password@db:5432/postgres?sslmode=disable"
    depends_on:
      - db
    networks:
      - vote-api-network

  web-client:
    build:
      context: web-client
    ports:
      - "3000:3000"
    environment:
      VOTE_API_BASE_URL: "http://vote-api:8080"
    networks:
      - vote-api-network

networks:
  vote-api-network: