name: CD Back

permissions:
  actions: read
  contents: read

on:
  workflow_run:
    workflows: ["CI Back"]
    branches: [main]
    types: 
      - completed

defaults:
  run:
    working-directory: vote-api

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./vote-api
          file: ./vote-api/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/vote-api:latest

      - name: Re-deploy Docker container
        run: curl ${{ secrets.RENDER_HOOK_BACK }}