name: CD Front

permissions:
  actions: read
  contents: read

on:
  workflow_run:
    workflows: ["CI Front"]
    branches: [main]
    types: 
      - completed

defaults:
  run:
    working-directory: web-client

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./web-client
          file: ./web-client/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/web-client:latest