name: CI Front
 
permissions:
  actions: read
  contents: read

on:
  push:
    branches:
      - main
  pull_request:

defaults:
  run:
    working-directory: web-client

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Install NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install Yarn
        run: npm install -g yarn

      - name: Install NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'yarn'
          cache-dependency-path: './web-client/yarn.lock'

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Run tests
        run: yarn test

  build:
    runs-on: ubuntu-latest
    needs: tests
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Install NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install Yarn
        run: npm install -g yarn

      - name: Install NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'yarn'
          cache-dependency-path: './web-client/yarn.lock'

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build project
        run: yarn build